apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  jwt-secret: "f59aecbaaf1e3731b53e5939b10980842b214f273ee5a79d3dfeb920019ee965"
  mongo-uri: "mongodb://mongo:27017/urlshortener"
  base-url: "http://localhost"
